# Generated by Django 5.0.2 on 2024-02-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'CategoriaGastos',
            },
        ),
        migrations.CreateModel(
            name='TiposGastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_gasto', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'TiposGastos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('apellido_usuario', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('ultima_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gasto', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.categoriagastos')),
                ('tipogasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.tiposgastos')),
            ],
            options={
                'db_table': 'Gastos',
            },
        ),
    ]
