# Generated by Django 5.0.2 on 2024-02-09 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0002_gastos_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('fecha_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('expiracion_conexion', models.DateTimeField(default=datetime.datetime(2024, 2, 9, 0, 24, 17, 12232, tzinfo=datetime.timezone.utc))),
                ('token_session', models.CharField(blank=True, max_length=100)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
                ('NumeroSocio', models.IntegerField()),
                ('Estado', models.IntegerField()),
            ],
            options={
                'db_table': 'SesionesActivas',
            },
        ),
    ]
