# Generated by Django 5.0.2 on 2024-02-09 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0003_sesionesactivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 0, 41, 56, 639566, tzinfo=datetime.timezone.utc)),
        ),
    ]
