# Generated by Django 5.0.2 on 2024-02-09 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0004_alter_sesionesactivas_expiracion_conexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionesactivas',
            name='NumeroSocio',
        ),
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 0, 54, 19, 498835, tzinfo=datetime.timezone.utc)),
        ),
    ]
