# Generated by Django 5.0.2 on 2024-02-09 23:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0005_remove_sesionesactivas_numerosocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 23, 51, 44, 790902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_gasto', models.IntegerField()),
                ('fecha_gasto', models.DateField(verbose_name='fecha egresos')),
                ('anotacion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.gastos')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Conexion.usuarios')),
            ],
            options={
                'db_table': 'Egresos',
            },
        ),
    ]
