# Generated by Django 5.0.2 on 2024-02-10 01:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0006_alter_sesionesactivas_expiracion_conexion_egresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposProductosFinancieros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_producto', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'TiposProductosFinancieros',
            },
        ),
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 1, 7, 15, 596581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProductosFinancieros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Conexion.usuarios')),
                ('tipoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.tiposproductosfinancieros')),
            ],
            options={
                'db_table': 'ProductosFinancieros',
            },
        ),
    ]
