# Generated by Django 5.0.2 on 2024-02-10 01:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0007_tiposproductosfinancieros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 1, 50, 29, 752193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_ingreso', models.IntegerField()),
                ('fecha_ingreso', models.DateField(verbose_name='fecha ingresos')),
                ('anotacion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('producto_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.productosfinancieros')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Conexion.usuarios')),
            ],
            options={
                'db_table': 'Ingresos',
            },
        ),
    ]
