# Generated by Django 5.0.2 on 2024-02-14 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0008_alter_sesionesactivas_expiracion_conexion_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mes', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha_registro')),
            ],
            options={
                'db_table': 'Meses',
            },
        ),
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 1, 12, 48, 996728, tzinfo=datetime.timezone.utc)),
        ),
    ]
