# Generated by Django 5.0.2 on 2024-02-14 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0009_meses_alter_sesionesactivas_expiracion_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meses',
            name='numero_mes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 1, 17, 28, 295390, tzinfo=datetime.timezone.utc)),
        ),
    ]
