# Generated by Django 5.0.2 on 2024-02-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0011_alter_gastos_nombre_gasto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionesactivas',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='sesionesactivas',
            name='expiracion_conexion',
        ),
    ]
