# Generated by Django 5.0.2 on 2024-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0012_remove_sesionesactivas_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
