# Generated by Django 5.0.2 on 2024-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0014_categoriagastos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagastos',
            name='nombre_categoria',
            field=models.CharField(max_length=200),
        ),
    ]
