# Generated by Django 5.0.2 on 2024-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0016_solicitudpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpassword',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha vencimiento'),
        ),
    ]
