# Generated by Django 5.0.2 on 2024-05-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0018_mediopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresosDistribucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('egresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.egresos')),
                ('mediopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conexion.mediopago')),
            ],
            options={
                'db_table': 'EgresosDistribucion',
            },
        ),
    ]
