# Generated by Django 5.0.2 on 2024-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0019_egresosdistribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
