# Generated by Django 5.0.2 on 2024-06-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conexion', '0020_mediopago_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesBeneficios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=200)),
                ('anotacion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Conexion.usuarios')),
            ],
            options={
                'db_table': 'EntidadesBeneficios',
            },
        ),
    ]
